dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

notifications:
  email: false

script:
  - go build -o bin/osctrl-tls cmd/tls/*.go
  - go build -o bin/osctrl-admin cmd/admin/*.go
  - go build -o bin/osctrl-cli cmd/cli/*.go
