# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12
    steps:
      - checkout

      - run: go build -buildmode=plugin -o plugins/logging_dispatcher_plugin.so plugins/logging_dispatcher/*.go
      - run: go build -buildmode=plugin -o plugins/db_logging_plugin.so plugins/db_logging/*.go
      - run: go build -buildmode=plugin -o plugins/graylog_logging_plugin.so plugins/graylog_logging/*.go
      - run: go build -buildmode=plugin -o plugins/splunk_logging_plugin.so plugins/splunk_logging/*.go
      - run: go build -o bin/osctrl-tls cmd/tls/*.go
      - run: go build -o bin/osctrl-admin cmd/admin/*.go
      - run: go build -o bin/osctrl-cli cmd/cli/*.go
