baseURL = "https://osctrl.net/"
languageCode = "en-us"
title = "osctrl: Fast and efficient operative system management"

theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "blue"
editURL = "https://github.com/jmpsec/osctrl/docs/edit/master/content/"
